name: Apply Supabase Migrations

# Trigger this workflow when changes are pushed to master in the migrations folder
on:
  push:
    branches:
      - master
    paths:
      - 'supabase/migrations/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Apply migrations
        run: npx supabase@latest db push --db-url "${{ secrets.SUPABASE_DB_URL }}" --debug
